In [7]:
import pandas as pd

df_turbines = pd.read_parquet(
    "../../data/processed/alta10_turbine_data_grouped.parquet"
)
df_turbines

turbine                  wtg150                                    \
variable            air_density blade_position_2 blade_position_3
utc_time
2026-01-01 08:00:00    1.092081        -1.056245        -0.643520
2026-01-01 08:10:00    0.800856        -1.077751        -0.680390
2026-01-01 08:20:00    1.089478        -0.445800        -0.039797
2026-01-01 08:30:00    0.800936        -1.205972        -0.786801
2026-01-01 08:40:00    1.090836        -1.205672        -0.786363
...                         ...              ...              ...
2026-02-01 07:10:00    1.053385         4.080153         4.090746
2026-02-01 07:20:00    1.052123         5.644671         5.642931
2026-02-01 07:30:00    1.052318        20.777641        20.777846
2026-02-01 07:40:00    1.054639        47.652470        47.758788
2026-02-01 07:50:00    1.055686        47.044416        47.044415

turbine                                                                  \
variable            blade_setpoint_position_1 blade_setpoint_position_2
utc_time
2026-01-01 08:00:00                  2.307242                 -0.892182
2026-01-01 08:10:00                  2.354385                 -0.845038
2026-01-01 08:20:00                  2.813232                 -0.386191
2026-01-01 08:30:00                       NaN                       NaN
2026-01-01 08:40:00                       NaN                       NaN
...                                       ...                       ...
2026-02-01 07:10:00                  4.318937                  4.094210
2026-02-01 07:20:00                  5.656648                  5.658021
2026-02-01 07:30:00                 20.714224                 20.714224
2026-02-01 07:40:00                 48.824902                 48.824902
2026-02-01 07:50:00                 47.975150                 47.975150

turbine                                                                        \
variable            blade_setpoint_position_3 nacelle_position real_power_a_c
utc_time
2026-01-01 08:00:00                 -0.471435       118.785714      672.60510
2026-01-01 08:10:00                 -0.424893       117.066667      541.30096
2026-01-01 08:20:00                  0.032674       118.812500      237.94884
2026-01-01 08:30:00                       NaN              NaN      503.22354
2026-01-01 08:40:00                       NaN       130.000000      444.42767
...                                       ...              ...            ...
2026-02-01 07:10:00                  4.104477       100.000000        0.05158
2026-02-01 07:20:00                  5.637986       105.000000        0.00000
2026-02-01 07:30:00                 20.533077              NaN        0.00000
2026-02-01 07:40:00                 48.752768       112.500000        0.00000
2026-02-01 07:50:00                 47.972260       113.500000        0.00000

turbine                                                   ...  \
variable            real_power_a_c_2 temperature_ambient  ...
utc_time                                                  ...
2026-01-01 08:00:00       670.286714            8.299405  ...
2026-01-01 08:10:00       542.747853            8.573889  ...
2026-01-01 08:20:00       239.185173            8.972823  ...
2026-01-01 08:30:00       504.556470            8.531316  ...
2026-01-01 08:40:00       444.157211            8.621079  ...
...                              ...                 ...  ...
2026-02-01 07:10:00         7.736964           18.960490  ...
2026-02-01 07:20:00              NaN           19.311193  ...
2026-02-01 07:30:00              NaN           19.256907  ...
2026-02-01 07:40:00              NaN           18.612710  ...
2026-02-01 07:50:00              NaN           18.322916  ...

turbine                       wtg197                                  \
variable            nacelle_position real_power_a_c real_power_a_c_2
utc_time
2026-01-01 08:00:00        62.500000    1232.199800      1229.936331
2026-01-01 08:10:00        59.000000     990.268700       990.641605
2026-01-01 08:20:00        58.666667    1074.207600      1074.568828
2026-01-01 08:30:00        67.333333    1108.804000      1108.957917
2026-01-01 08:40:00        67.100000    1124.448100      1123.277779
...                              ...            ...              ...
2026-02-01 07:10:00        56.869565      84.739070        84.595000
2026-02-01 07:20:00        52.705882      76.168015        76.249686
2026-02-01 07:30:00        52.352941      80.234050        80.145644
2026-02-01 07:40:00        52.081081     101.994514       101.915690
2026-02-01 07:50:00        49.000000     159.606050       159.485644

turbine                                                             \
variable            temperature_ambient temperature_ambient_merged
utc_time
2026-01-01 08:00:00            6.258348                   6.258348
2026-01-01 08:10:00            6.331188                   6.331188
2026-01-01 08:20:00            6.456590                   6.456590
2026-01-01 08:30:00            6.545990                   6.545990
2026-01-01 08:40:00            6.563307                   6.563307
...                                 ...                        ...
2026-02-01 07:10:00           17.263000                  17.263000
2026-02-01 07:20:00           17.176825                  17.176825
2026-02-01 07:30:00           17.267698                  17.267698
2026-02-01 07:40:00           17.342490                  17.342490
2026-02-01 07:50:00           17.305105                  17.305105

turbine                                                                       \
variable            theoretical_power wind_direction wind_direction_relative
utc_time
2026-01-01 08:00:00        1418.43810      54.739130               -6.454545
2026-01-01 08:10:00         817.20810      52.763514               -5.510949
2026-01-01 08:20:00        1234.45760      53.654930               -4.808824
2026-01-01 08:30:00         843.87770      60.771812               -6.313869
2026-01-01 08:40:00        1250.21330      60.806897               -6.318519
...                               ...            ...                     ...
2026-02-01 07:10:00         119.84952      46.037500               -6.540146
2026-02-01 07:20:00         113.67615      43.587500               -8.986014
2026-02-01 07:30:00         116.28876      45.381250               -6.573427
2026-02-01 07:40:00         131.63934      44.648045               -6.852113
2026-02-01 07:50:00         201.76222      43.262774               -6.838235

turbine
variable            wind_speed wind_speed_2
utc_time
2026-01-01 08:00:00   8.669571     8.664497
2026-01-01 08:10:00   8.006839     8.000924
2026-01-01 08:20:00   8.203914     8.207936
2026-01-01 08:30:00   8.110932     8.099642
2026-01-01 08:40:00   8.245337     8.257563
...                        ...          ...
2026-02-01 07:10:00   4.143207     4.146245
2026-02-01 07:20:00   4.064322     4.068977
2026-02-01 07:30:00   4.100440     4.096376
2026-02-01 07:40:00   4.266240     4.268150
2026-02-01 07:50:00   4.761758     4.771564

[4464 rows x 798 columns]

In [8]:
df_turbines["wtg150"].head()

variable,air_density,blade_position_2,blade_position_3,blade_setpoint_position_1,blade_setpoint_position_2,blade_setpoint_position_3,nacelle_position,real_power_a_c,real_power_a_c_2,temperature_ambient,temperature_ambient_merged,theoretical_power,wind_direction,wind_direction_relative,wind_speed,wind_speed_2
utc_time,,,,,,,,,,,,,,,,
2026-01-01 08:00:00,1.092081,-1.056245,-0.643520,2.307242,-0.892182,-0.471435,118.785714,672.60510,670.286714,8.299405,8.299405,746.68463,115.629870,-1.392857,6.906036,6.907681
2026-01-01 08:10:00,0.800856,-1.077751,-0.680390,2.354385,-0.845038,-0.424893,117.066667,541.30096,542.747853,8.573889,8.573889,466.00030,107.211538,-10.056738,6.609679,6.592723
2026-01-01 08:20:00,1.089478,-0.445800,-0.039797,2.813232,-0.386191,0.032674,118.812500,237.94884,239.185173,8.972823,8.972823,292.86000,122.834356,0.734694,5.210308,5.229490
2026-01-01 08:30:00,0.800936,-1.205972,-0.786801,NaN,NaN,NaN,NaN,503.22354,504.556470,8.531316,8.531316,443.03992,121.493151,-6.506849,6.510418,6.512685
2026-01-01 08:40:00,1.090836,-1.205672,-0.786363,NaN,NaN,NaN,130.000000,444.42767,444.157211,8.621079,8.621079,500.71185,121.117241,-8.119718,6.093416,6.106378